# Generated by Django 2.2.4 on 2021-04-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='topping_type',
            new_name='topping',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='nutritional',
        ),
    ]
